name: Build for macOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew install libx11-xcb libxcursor-xcb libxi-xcb
      - name: Generate Makefiles
        run: |
          cmake -S. -B build -G Xcode \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_UI=on \
            -DENABLE_CCACHE=on \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=./skia \
            -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \
            -DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib
      - name: Compiling
        run: |
          cd build && xcodebuild
      - uses: actions/upload-artifact@v3
        with:
          name: aseprite
          path: |
            build/Release/aseprite.app
